### ISSUE TITLE
Directory missing from .gitignore

### ISSUE THREAD

**Issue by krissrex** [haraldfw/tools#1]
## wow

"_/StatsEditor/bin_" should perhaps be in _.gitignore_.

**Comment by haraldfw** [comment]
Such thanks. Hasnt setup gitignore yit. Tux!

Sent from Windows Mail

From: krissrex
Sent: ‎Monday‎, ‎August‎ ‎25‎, ‎2014 ‎10‎:‎55‎ ‎PM
To: haraldfw/tools

wow

"/StatsEditor/bin" should perhaps be in .gitignore.
